# .travis.yml
language: node_js

node_js:
  - '0.10'
  - '0.12'

before_script:
  - psql -c "create database moron_test;" -U postgres
  - mysql -e "create database moron_test;"

after_script:
  - npm run-script coveralls

notifications:
  email: false
